package:
  name: threebodyjg
  version: v1.0.2

source:
  git_rev: v1.0.2
  git_url: https://github.com/astrojarred/threebodyjg

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - wxpython

about:
  home: https://github.com/astrojarred/threebodyjg
  license: GPL3
  license_file: LICENSE
  description: 'A three-body simulation'